language: c
before_install:
  - cd MOTOR_MANAGEMENT_V0_1/MOTOR_MANAGEMENT_V0_1
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script:
  - make clean
  - make
notifications:
  email:
    recipients:
      - benjamin.marty@gmail.com
    on_success: always # default: change
    on_failure: always # default: always